version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: support_tickets_app
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: support_tickets_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: support_tickets_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: support_tickets_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network:
